name: 'Install dependencies'
description: Install node and bun, then run bun install

inputs:
  node-version: # id of input
    description: 'Node version'
    required: false
    default: 20

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        #cache: 'bun'
        registry-url: 'https://registry.npmjs.org'

    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v4
      with:
        lookup-only: true
        path: '**/node_modules'
        key: bun-${{ hashFiles('bun.lockb','bun.lock') }}

    - name: Install packages
      run: bun install --frozen-lockfile
      shell: bash
