name: Run e2e Tests for nx-quarkus

on:
  push:
    branches: [ develop ]
    paths:    [ "packages/nx-quarkus/**" ]
  pull_request:
    branches: [ develop ]
    paths:    [ "packages/nx-quarkus/**" ]

jobs:
  run_e2e:
    name: Run e2e Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: NPM cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ env.cache-name }}-

      - name: Install packages
        run: npm ci

      - name: Run e2e tests
        env:
          NX_E2E_CI_CACHE_KEY: e2e-gha-${{ matrix.os }}-${{ matrix.node-version }}
          NX_VERBOSE_LOGGING: ${{ 'true' }}
          NX_E2E_SKIP_BUILD_CLEANUP: ${{ 'true' }}
          NX_E2E_SKIP_DAEMON_CLEANUP: ${{ 'true' }}
        run: |
          npm run ts-node -P ./tools/tsconfig.tools.json ./tools/patch-nx-project.ts
          npm run e2e nx-quarkus-e2e